// Static seed data for MVP demo (no DB required for sharing)

export const DEMO_FAMILY = {
  id: "sharma-family",
  name: "Sharma Family",
  inviteCode: "SHARMA-X7K2",
  region: "Chandigarh",
  memberCount: 8,
};

export const DEMO_RITUALS = [
  {
    id: "namkaran",
    name: "Namkaran",
    subtitle: "Naming Ceremony",
    category: "Naming",
    religion: ["Hindu"],
    region: "North India",
    language: "Hindi/Sanskrit",
    performedCount: 3,
    steps: [
      "Purify the space with Ganga jal and light the diya",
      "Seat the baby on the mother's lap facing East",
      "Priest performs Ganapati puja to remove obstacles",
      "Nakshatra (birth star) is confirmed with the horoscope",
      "Father whispers the chosen name into baby's right ear",
      "Name is announced to the family with a conch blow",
      "Baby is shown the sun or moon",
      "Priest recites naming mantras and blessings",
      "Gifts of gold and silver are exchanged",
      "Family feast — kheer and puri are served",
      "Elder women perform aarti of the baby",
      "Name is registered in the family panchangam",
    ],
    samagri: [
      { item: "Ghee (clarified butter)", quantity: "500g", purpose: "For havan/fire ritual" },
      { item: "Raw rice (akshat)", quantity: "2 kg", purpose: "Offerings and aarti" },
      { item: "Turmeric powder", quantity: "100g", purpose: "Purification" },
      { item: "Kumkum (sindoor)", quantity: "50g", purpose: "Tilak and blessings" },
      { item: "Sandalwood paste", quantity: "100g", purpose: "Applied on baby's forehead" },
      { item: "Betel leaves", quantity: "21 pieces", purpose: "Ritual offering" },
      { item: "Coconut (whole)", quantity: "5 nos", purpose: "Auspicious offering" },
      { item: "Flowers — marigold, rose", quantity: "2 kg", purpose: "Decoration and offerings" },
      { item: "Incense sticks", quantity: "2 packets", purpose: "Fragrance and purification" },
      { item: "Camphor (kapoor)", quantity: "50g", purpose: "Aarti" },
      { item: "Honey + milk", quantity: "250ml each", purpose: "Panchamrit for baby" },
      { item: "New cloth — yellow/white", quantity: "1 meter", purpose: "Baby's first clothing" },
      { item: "Silver coin", quantity: "1 no", purpose: "Given to baby as first gift" },
    ],
    mantras: [
      {
        devanagari: "ॐ नमः शिवाय। आयुष्मान् भव। सर्वेषां स्वस्तिर्भवतु।",
        transliteration: "Om Namah Shivaya. Aayushmaan bhava. Sarveshaam svastir bhavatu.",
        meaning: "I bow to Shiva. May you be blessed with long life. May all beings be well.",
      },
    ],
    elderNotes:
      "In our family, we always choose the name based on the Nakshatra's first syllable as per our kuldevi's tradition. Dadi says the name should be whispered 3 times, not once. The naming should always happen in the morning hours. — Rajesh Sharma",
    preparationDays: 7,
    isTemplate: true,
  },
  {
    id: "annaprashan",
    name: "Annaprashan",
    subtitle: "First Rice Feeding Ceremony",
    category: "Birth",
    religion: ["Hindu"],
    region: "Bengal / Pan India",
    language: "Sanskrit / Bengali",
    performedCount: 2,
    steps: [
      "Bathe and dress the baby in new clothes",
      "Set up the puja space with a silver or brass plate",
      "Priest performs Ganapati puja",
      "Rice, kheer (sweet rice), and five tastes are prepared",
      "Baby is seated on grandfather's lap (maternal, in Bengal)",
      "Priest chants annaprashan mantras",
      "First spoonful of kheer fed by the priest",
      "Then by father, then mother, then grandparents",
      "Other family members take turns feeding",
      "Place objects before baby — book, clay, pen, food (fate divination)",
      "Family feast with 5-course Bengali/North Indian meal",
      "Aarti and blessings for the baby",
    ],
    samagri: [
      { item: "Rice (new crop, preferably)", quantity: "1 kg", purpose: "First solid food" },
      { item: "Milk", quantity: "1 liter", purpose: "For kheer preparation" },
      { item: "Sugar / jaggery", quantity: "200g", purpose: "Sweetening kheer" },
      { item: "Silver spoon", quantity: "1 no", purpose: "First feeding spoon" },
      { item: "Banana leaf", quantity: "2 nos", purpose: "Traditional serving plate" },
      { item: "Five taste items (sweet, salt, sour, bitter, spice)", quantity: "Pinch each", purpose: "Exposure to all tastes" },
      { item: "Flowers and garlands", quantity: "1 kg", purpose: "Decoration" },
      { item: "Incense + diya", quantity: "1 set", purpose: "Puja" },
    ],
    mantras: [],
    elderNotes:
      "In the Sharma family, we use a silver plate handed down from Dadi's mother. The kheer must be made by the baby's grandmother, not anyone else.",
    preparationDays: 5,
    isTemplate: true,
  },
  {
    id: "griha-pravesh",
    name: "Griha Pravesh",
    subtitle: "Housewarming Puja",
    category: "Housewarming",
    religion: ["Hindu"],
    region: "Pan India",
    language: "Sanskrit",
    performedCount: 1,
    steps: [
      "Determine auspicious muhurat (timing) with family priest",
      "Decorate entrance with mango leaves and marigold torans",
      "Apply rangoli at the entrance with auspicious motifs",
      "Kalash sthapana — place a brass/copper pot with coconut",
      "Vastu puja performed in northeast corner of home",
      "Havan (fire ritual) performed by priest",
      "Wife enters first carrying a pot of rice, symbolizing prosperity",
      "Husband carries the Ganesha idol into the home",
      "Boil milk until it overflows — symbol of abundance",
      "Puja in each room, especially kitchen and bedroom",
      "Aarti and distribution of prasad",
      "Feast for family and neighbors",
    ],
    samagri: [
      { item: "Brass kalash with coconut", quantity: "1 set", purpose: "Central ritual vessel" },
      { item: "Mango leaves", quantity: "50 leaves", purpose: "Decoration and auspice" },
      { item: "Marigold flowers", quantity: "3 kg", purpose: "Toran and decoration" },
      { item: "Rangoli colors", quantity: "1 set", purpose: "Entrance design" },
      { item: "Havan samagri", quantity: "500g", purpose: "Fire ritual materials" },
      { item: "Ghee", quantity: "1 kg", purpose: "Havan offerings" },
      { item: "Raw milk", quantity: "2 liters", purpose: "Boiling ritual" },
      { item: "Rice (uncooked)", quantity: "5 kg", purpose: "Carried by lady of house" },
    ],
    mantras: [
      {
        devanagari: "ॐ वास्तु पुरुषाय नमः। गृहे सुखं समृद्धिं च देहि।",
        transliteration: "Om Vaastu Purushaya Namah. Grahe sukham samriddhim cha dehi.",
        meaning: "Salutations to Vastu Purusha. Grant happiness and prosperity to this home.",
      },
    ],
    elderNotes: "Our family follows the tradition that the wife must enter first carrying an overflowing kalash of rice. The threshold must not be stepped on — step over it.",
    preparationDays: 14,
    isTemplate: true,
  },
];

export const DEMO_FESTIVALS = [
  {
    id: "guru-purnima",
    name: "Guru Purnima",
    date: "2026-07-29",
    religion: "Hindu",
    significance: "A sacred day to honor spiritual and academic teachers. Disciples fast, visit their guru, and seek blessings. Observed on the full moon day of Ashadha month.",
    ritualSteps: [
      "Wake up early, take a purifying bath",
      "Visit your guru or teacher",
      "Offer flowers, fruits, and dakshina",
      "Read or listen to Guru Gita",
      "Fast or eat sattvic food only",
      "Evening puja and aarti",
    ],
    food: "Sattvic food — fruits, milk, kheer. Many observe a full fast.",
    samagri: ["Flowers", "Fruits", "Dakshina (gift)", "Dhoop/Agarbatti", "Diya"],
  },
  {
    id: "raksha-bandhan",
    name: "Raksha Bandhan",
    date: "2026-08-28",
    religion: "Hindu",
    significance: "Sisters tie a sacred thread (rakhi) on their brother's wrist, symbolizing love and protection. Brothers give gifts and promise to protect their sisters.",
    ritualSteps: [
      "Sister performs aarti of brother",
      "Applies tilak on brother's forehead",
      "Ties rakhi on brother's right wrist",
      "Brother gives gift and promises protection",
      "Sweets exchanged and feast together",
    ],
    food: "Sweets — ladoo, barfi, kheer. Special family meal.",
    samagri: ["Rakhi thread", "Roli/kumkum", "Akshat (rice)", "Diya", "Sweets"],
  },
  {
    id: "janmashtami",
    name: "Janmashtami",
    date: "2026-09-04",
    religion: "Hindu",
    significance: "Celebrates the birth of Lord Krishna at midnight. Devotees fast the entire day, sing bhajans, and celebrate with joy when the clock strikes midnight.",
    ritualSteps: [
      "Fast from sunrise",
      "Decorate jhula (swing) for Krishna idol",
      "Sing bhajans and kirtans through the day",
      "At midnight: bathe the Krishna idol",
      "Place baby Krishna in the jhula",
      "Blow conch and ring bells to celebrate",
      "Break fast with panchamrit and prasad",
    ],
    food: "Panchamrit (milk, curd, honey, ghee, sugar). After midnight: fruits, sweets, makhana.",
    samagri: ["Krishna idol/murti", "Jhula (swing)", "Panchamrit ingredients", "Flowers", "Conch"],
  },
  {
    id: "ganesh-chaturthi",
    name: "Ganesh Chaturthi",
    date: "2026-09-14",
    religion: "Hindu",
    significance: "10-day festival celebrating the birth of Lord Ganesha, the remover of obstacles. Families install a Ganesha idol and perform daily pujas.",
    ritualSteps: [
      "Bring home the Ganesha idol (preferably eco-friendly clay)",
      "Install on a decorated platform facing east/north",
      "Daily puja with 21 durva grass blades",
      "Offer modak (sweet dumpling) — Ganesha's favorite",
      "Aarti morning and evening",
      "On the 10th day — Visarjan (immersion in water)",
    ],
    food: "Modak (steamed or fried), karanji, coconut-based sweets.",
    samagri: ["Ganesha idol (clay)", "21 durva grass", "Modak", "Red flowers (hibiscus)", "Coconut"],
  },
  {
    id: "navratri",
    name: "Navratri",
    date: "2026-10-11",
    religion: "Hindu",
    significance: "Nine nights of worship of Goddess Durga and her nine forms (Navadurga). Celebrated with fasting, garba/dandiya dance, and daily puja.",
    ritualSteps: [
      "Set up the Devi altar on the first day",
      "Plant jau (barley) in a pot symbolizing growth",
      "Perform aarti twice daily for 9 days",
      "Fast or eat vrat foods",
      "Observe Kanya Puja on Ashtami/Navami",
      "Feed nine young girls as Navadurga",
      "Participate in garba/dandiya in the evenings",
    ],
    food: "Vrat food: sabudana khichdi, kuttu poori, singhare ka halwa, fruits.",
    samagri: ["Durga murti/photo", "Red cloth/chunri", "Coconut", "Red flowers", "Jau seeds", "Ghee diya"],
  },
  {
    id: "diwali",
    name: "Diwali",
    date: "2026-11-08",
    religion: "Hindu",
    significance: "Festival of lights celebrating the return of Lord Rama to Ayodhya. Five-day celebration with diyas, fireworks, Lakshmi puja, and family gatherings.",
    ritualSteps: [
      "Clean and whitewash the house (days before)",
      "Make rangoli at the entrance",
      "Light clay diyas at dusk around the entire home",
      "Perform Lakshmi-Ganesha puja at night",
      "Light fireworks (safely)",
      "Exchange sweets and gifts with family and neighbors",
      "On Dhanteras: buy gold or silver",
    ],
    food: "Mithai: kaju katli, ladoo, gulab jamun. Special halwa-puri.",
    samagri: ["Clay diyas (minimum 21)", "Mustard oil or ghee", "Cotton wicks", "Lakshmi-Ganesha idol", "Rangoli colors", "Sweets"],
  },
];

export const DEMO_MEMBERS = [
  { id: "1", name: "Rajesh Sharma", role: "Admin", relation: "Papa", religion: "Hindu", region: "Chandigarh", initials: "RS", color: "saffron" },
  { id: "2", name: "Priya Sharma", role: "Elder", relation: "Maa", religion: "Hindu", region: "Chandigarh", initials: "PS", color: "forest" },
  { id: "3", name: "Arjun Sharma", role: "Parent", relation: "Son", religion: "Hindu", region: "Gurugram", initials: "AS", color: "saffron" },
  { id: "4", name: "Neha Sharma", role: "Parent", relation: "Daughter", religion: "Hindu", region: "Mumbai", initials: "NS", color: "forest" },
  { id: "5", name: "Kavya Sharma", role: "Contributor", relation: "Granddaughter", religion: "Hindu", region: "Chandigarh", initials: "KS", color: "saffron" },
  { id: "6", name: "Vivek Sharma", role: "Contributor", relation: "Grandson", religion: "Hindu", region: "Chandigarh", initials: "VS", color: "forest" },
  { id: "7", name: "Meena Sharma", role: "Viewer", relation: "Bua", religion: "Hindu", region: "Jaipur", initials: "MS", color: "saffron" },
  { id: "8", name: "Deepak Sharma", role: "Viewer", relation: "Chacha", religion: "Hindu", region: "Chandigarh", initials: "DS", color: "forest" },
];
